quarkus.datasource.db-kind=postgresql

quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

quarkus.http.port=${HTTP_PORT:8080}
quarkus.jackson.write-dates-as-timestamps=false

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.db-name=cookify
%dev.quarkus.datasource.devservices.username=cookify
%dev.quarkus.datasource.devservices.password=cookify
%dev.quarkus.datasource.devservices.reuse=false

%prod.quarkus.datasource.username=${DB_USERNAME:cookify}
%prod.quarkus.datasource.password=${DB_PASSWORD:cookify}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/cookify}
