name: CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        env:
          VERSION: ${{ github.ref_name }}
          IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: |
          docker build . --file ./docker/Dockerfile --tag "$IMAGE_NAME"
          docker push "$IMAGE_NAME"
